/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Style = "Header" | "Emphasis" | "Normal";
export type Text = string;
export type Line2 = string;
export type Body = Line2[];

/**
 * A simple generator for cover letters.
 */
export interface CoverLetterEdit {
  Header: Line[];
  To?: Line1[];
  Body?: Body;
  [k: string]: unknown;
}
export interface Line {
  style?: Style;
  text?: Text;
  [k: string]: unknown;
}
export interface Line1 {
  style?: Style;
  text?: Text;
  [k: string]: unknown;
}
