name: Setup

description: Setup Node.js, cache and install dependencies

inputs:
  node_version:
    description: Node.js version
    required: false
    default: '16'
  token:
    description: GitHub Token
    required: false
    default: ${{ secrets.GITHUB_TOKEN }}

runs:
  using: composite
  steps:
    - name: Checkout all commits
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}
        fetch-depth: 0

    # - name: Setup git user to "🤖 JSCutlery Bot"
    #   shell: bash
    #   run: git config user.email "-" && git config user.name "🤖 JSCutlery Bot"

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        # This doesn't just set the registry url, but also sets
        # the right configuration in .npmrc that reads NPM token
        # from NPM_AUTH_TOKEN environment variable.
        # It actually creates a .npmrc in a temporary folder
        # and sets the NPM_CONFIG_USERCONFIG environment variable.
        registry-url: https://registry.npmjs.org
    - name: Cache
      uses: actions/cache@v2
      id: npm-cache
      with:
        path: node_modules
        key: nodemodules-${{ hashFiles('yarn.lock') }}
        restore-keys: nodemodules-
    - name: Cache ~/.cache
      id: cache
      uses: actions/cache@v3
      with:
        path: ~/.cache
        key: ${{ runner.os }}-cache-${{ hashFiles('./yarn.lock') }}
    - name: yarn install
      shell: bash
      run: yarn install --frozen-lockfile
