name: reviewdog
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: errata-ai/vale-action@reviewdog
        if: github.event_name == "pull_request"
        with:
          reporter: github-pr-review
          files: apps/portfolio/content
          filter_mode: nofilter
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - uses: errata-ai/vale-action@reviewdog
        if: github.event_name != "pull_request"
        with:
          reporter: github-check
          files: apps/portfolio/content
          filter_mode: nofilter
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
