name: CI
on: [push]
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: yarn build
        run: yarn build
      - name: run Lighthouse CI
        run: |
          yarn install -g @lhci/cli@0.8.x
          lhci autorun
