name: Release
on:
  push:
    branches:
      - main
      - alpha

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^((?!skip ci).)*$'
          flags: 's'
          error: 'Skipping for release commit.'

      - uses: actions/checkout@v2
        # with:
        #   persist-credentials: false

      # - name: Configure CI Git User
      #   run: |
      #     git config --global user.name 'TheUnderScorer'
      #     git config --global user.email 'przemyslawzydek@gmail.com'
      #     git remote set-url origin https://TheUnderScorer:$GITHUB_TOKEN@github.com/TheUnderScorer/time-neko
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cache
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: nodemodules-${{ hashFiles('yarn.lock') }}
          restore-keys: nodemodules-

      - name: Install npm dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          yarn install

      # - name: Build apps
      #   run: |
      #     npx nx run-many --target=build --maxParallel=1 --all

      - name: Prerelease
        run: yarn release --configuration=prerelease
        if: github.ref == 'refs/heads/alpha'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        run: yarn release
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
